[package]
name = "rusty_quadtree"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "quadtree"
path = "src/quadtree.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
